Document: equilibrium-release
Title: Debian equilibrium-release Manual
Author: <insert document author here>
Abstract: This manual describes what equilibrium-release is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/equilibrium-release/equilibrium-release.sgml.gz

Format: postscript
Files: /usr/share/doc/equilibrium-release/equilibrium-release.ps.gz

Format: text
Files: /usr/share/doc/equilibrium-release/equilibrium-release.text.gz

Format: HTML
Index: /usr/share/doc/equilibrium-release/html/index.html
Files: /usr/share/doc/equilibrium-release/html/*.html
